<a href="https://colab.research.google.com/github/lightfury36/Natural-Language-Processsing/blob/main/Word_embedding_techniques_using_Embedding_Layer_in_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot


In [ ]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
voc_size = 10000

##One Hot Representation##


In [ ]:
onehot_repr = [one_hot(words, voc_size)for words in sent]
print(onehot_repr)

[[2512, 9142, 7095, 1121], [2512, 9142, 7095, 8979], [2512, 3909, 7095, 7886], [4018, 5928, 3482, 7291, 2377], [4018, 5928, 3482, 7291, 2175], [9418, 2512, 4713, 7095, 3096], [7258, 1574, 5971, 7291]]


##Word Embedding Represntation##

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [ ]:
import numpy as np

In [ ]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2512 9142 7095 1121]
 [   0    0    0    0 2512 9142 7095 8979]
 [   0    0    0    0 2512 3909 7095 7886]
 [   0    0    0 4018 5928 3482 7291 2377]
 [   0    0    0 4018 5928 3482 7291 2175]
 [   0    0    0 9418 2512 4713 7095 3096]
 [   0    0    0    0 7258 1574 5971 7291]]


In [ ]:
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

[[[ 0.04378453 -0.03887673  0.03939677 -0.04594499  0.0036945
   -0.03274553 -0.00826691 -0.03199642  0.01648827  0.0081693 ]
  [ 0.04378453 -0.03887673  0.03939677 -0.04594499  0.0036945
   -0.03274553 -0.00826691 -0.03199642  0.01648827  0.0081693 ]
  [ 0.04378453 -0.03887673  0.03939677 -0.04594499  0.0036945
   -0.03274553 -0.00826691 -0.03199642  0.01648827  0.0081693 ]
  [ 0.04378453 -0.03887673  0.03939677 -0.04594499  0.0036945
   -0.03274553 -0.00826691 -0.03199642  0.01648827  0.0081693 ]
  [ 0.01149422  0.00053829  0.03301844 -0.01049735  0.03413392
    0.00722028 -0.0474209   0.01215713 -0.02963513  0.0068366 ]
  [-0.04133415 -0.00777923 -0.02509756 -0.015553   -0.04474722
   -0.0276332   0.01074631 -0.03517505  0.02174715  0.01711829]
  [ 0.02882898 -0.04417856  0.04314912 -0.01399241  0.02303106
    0.03709619 -0.00475375 -0.00867531  0.04723435  0.01888945]
  [-0.04821235  0.04400856 -0.03738451  0.04191348 -0.03670205
   -0.01549381 -0.00058086  0.02564828 -0.00929371 -

In [ ]:
len((model.predict(embedded_docs)))

7

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 2512, 9142, 7095, 1121], dtype=int32)

In [ ]:
print(model.predict(embedded_docs[0]))

[[[ 0.04378453 -0.03887673  0.03939677 -0.04594499  0.0036945
   -0.03274553 -0.00826691 -0.03199642  0.01648827  0.0081693 ]]

 [[ 0.04378453 -0.03887673  0.03939677 -0.04594499  0.0036945
   -0.03274553 -0.00826691 -0.03199642  0.01648827  0.0081693 ]]

 [[ 0.04378453 -0.03887673  0.03939677 -0.04594499  0.0036945
   -0.03274553 -0.00826691 -0.03199642  0.01648827  0.0081693 ]]

 [[ 0.04378453 -0.03887673  0.03939677 -0.04594499  0.0036945
   -0.03274553 -0.00826691 -0.03199642  0.01648827  0.0081693 ]]

 [[ 0.01149422  0.00053829  0.03301844 -0.01049735  0.03413392
    0.00722028 -0.0474209   0.01215713 -0.02963513  0.0068366 ]]

 [[-0.04133415 -0.00777923 -0.02509756 -0.015553   -0.04474722
   -0.0276332   0.01074631 -0.03517505  0.02174715  0.01711829]]

 [[ 0.02882898 -0.04417856  0.04314912 -0.01399241  0.02303106
    0.03709619 -0.00475375 -0.00867531  0.04723435  0.01888945]]

 [[-0.04821235  0.04400856 -0.03738451  0.04191348 -0.03670205
   -0.01549381 -0.00058086  0.02564828

In [ ]:
len(model.predict(embedded_docs[0]))

8